# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-31 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_count', models.IntegerField(verbose_name='\u9605\u8bfb\u6570')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Paper', verbose_name='\u6587\u7ae0')),
            ],
        ),
    ]
