# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-31 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_readcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='readcount',
            name='good_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
