# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 10:22
from __future__ import unicode_literals, absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhwiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipaper',
            name='url',
            field=models.TextField(default='', verbose_name='url'),
            preserve_default=False,
        ),
    ]
